const img={
 cleanser:"https://images.pexels.com/photos/14836428/pexels-photo-14836428.jpeg?auto=compress&cs=tinysrgb&w=900",
 serum:"https://images.pexels.com/photos/9496260/pexels-photo-9496260.jpeg?auto=compress&cs=tinysrgb&w=900",
 lip:"https://images.pexels.com/photos/1213558/pexels-photo-1213558.jpeg?auto=compress&cs=tinysrgb&w=900",
 mask:"https://images.pexels.com/photos/10612343/pexels-photo-10612343.jpeg?auto=compress&cs=tinysrgb&w=900",
 mist:"https://calmedi.id/wp-content/uploads/2021/08/Hydra-Face-Mist-70-mllll.png",
 brush:"https://images.pexels.com/photos/15898031/pexels-photo-15898031.jpeg?auto=compress&cs=tinysrgb&w=900"
};
export const products=[
{id:"cleanser",name:"Daily Glow Cleanser",category:"Skincare",price:58900,shortDescription:"Limpieza suave para comenzar tu ritual.",description:"Producto demo para validar la experiencia.",benefits:["Limpieza diaria","Sensación fresca"],ingredients:"Información pendiente del producto real.",usage:"Aplicar sobre piel húmeda, masajear y retirar.",presentation:"150 ml",variants:[{id:"150ml",name:"150 ml",price:58900,sku:"DEMO-CL-150"}],image:img.cleanser,imageLabel:"DEMO"},
{id:"serum",name:"Radiance Serum",category:"Skincare",price:84900,oldPrice:94900,shortDescription:"Sérum demo para una rutina luminosa.",description:"Producto demo para validar promociones.",benefits:["Textura ligera","Acabado luminoso"],ingredients:"Información pendiente del producto real.",usage:"Aplicar unas gotas después de limpiar.",presentation:"30 ml",variants:[{id:"30ml",name:"30 ml",price:84900,sku:"DEMO-RS-30"}],image:img.serum,imageLabel:"DEMO"},
{id:"lip",name:"Soft Vibe Lip",category:"Maquillaje",price:62900,shortDescription:"Color demo para llevar tu look a otro nivel.",description:"Producto demo con variantes de tono.",benefits:["Color modulable","Textura confortable"],ingredients:"Información pendiente del producto real.",usage:"Aplicar directamente sobre los labios.",presentation:"4 g",variants:[{id:"nude",name:"Nude",price:62900,sku:"DEMO-L-N"},{id:"rose",name:"Rose",price:62900,sku:"DEMO-L-R"},{id:"berry",name:"Berry",price:64900,sku:"DEMO-L-B"}],image:img.lip,imageLabel:"DEMO"},
{id:"mask",name:"Reset Face Mask",category:"Skincare",price:71900,shortDescription:"Mascarilla demo para un momento de reset.",description:"Producto demo para validar beneficios y uso.",benefits:["Autocuidado","Rutina semanal"],ingredients:"Información pendiente del producto real.",usage:"Aplicar una capa uniforme según instrucciones reales.",presentation:"75 g",variants:[{id:"75g",name:"75 g",price:71900,sku:"DEMO-M-75"}],image:img.mask,imageLabel:"DEMO"},
{id:"mist",name:"Hydra Mist",category:"Skincare",price:54900,shortDescription:"Bruma demo para refrescar tu rutina.",description:"Producto demo para validar navegación.",benefits:["Refrescante","Formato portátil"],ingredients:"Información pendiente del producto real.",usage:"Rociar a distancia sobre el rostro.",presentation:"100 ml",variants:[{id:"100ml",name:"100 ml",price:54900,sku:"DEMO-HM-100"}],image:img.mist,imageLabel:"DEMO"},
{id:"brush",name:"Essential Brush",category:"Accesorios",price:39900,shortDescription:"Accesorio demo para completar tu ritual.",description:"Producto demo para validar categorías.",benefits:["Práctico","Versátil"],ingredients:null,usage:"Usar según aplicación deseada.",presentation:"1 unidad",variants:[{id:"unit",name:"1 unidad",price:39900,sku:"DEMO-B-01"}],image:img.brush,imageLabel:"DEMO"}];
export const categories=["Todos",...new Set(products.map(p=>p.category))];